"""Offline regression tests over recorded replay fixtures.

These tests never touch the network, an API key or a model.  They re-run the
deterministic auditor over answers that were really produced by the pipeline
and assert the recorded scores are reproduced.  That separation is the point:
if the evaluator drifts, these tests fail even when the provider is down.

The fixtures are generated by ``export_replay_fixtures.py`` from real runs, so
they include provider failures and malformed answers rather than only the
happy path.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
FIXTURE_PATH = ROOT / "tests" / "fixtures" / "replay_fixtures.json"


def load_fixtures() -> list[dict]:
    payload = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    return payload["fixtures"]


def load_fixture_cases() -> dict:
    """Every case the fixtures refer to, across all recorded snapshots.

    The single-hop and composite multi-hop cases live in separate snapshot
    files.  Reading only the first (as an earlier version did) made every
    multi-hop fixture fail with a KeyError rather than replaying.
    """
    from src.frozen_evidence import load_cases

    payload = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    paths = payload.get("snapshots") or [str(ROOT / "data" / "frozen_retrieval_cases.jsonl")]
    cases: dict = {}
    for path in paths:
        for question_id, case in load_cases(Path(path)).items():
            cases.setdefault(question_id, case)
    return cases


@pytest.fixture(scope="module")
def fixtures() -> list[dict]:
    return load_fixtures()


def test_fixture_file_matches_current_audit_version():
    # A fixture scored by different rules is not a valid regression baseline.
    from src.frozen_evidence import AUDIT_VERSION

    payload = json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))
    assert payload["audit_version"] == AUDIT_VERSION, (
        "fixtures were exported under a different audit version; "
        "re-export with export_replay_fixtures.py before trusting these tests"
    )


def test_fixtures_cover_provider_failures_and_successes(fixtures):
    statuses = {fixture["status"] for fixture in fixtures}
    assert "completed" in statuses
    # Failure shapes must stay represented, otherwise the suite silently
    # becomes a happy-path-only check.
    assert statuses & {"provider_timeout", "provider_error"}


def test_fixtures_cover_refusal_and_ambiguity_cases(fixtures):
    ids = {fixture["question_id"] for fixture in fixtures}
    assert any("miss" in qid for qid in ids), "no insufficient-context case"
    assert any("ambiguous" in qid for qid in ids), "no ambiguous case"


def test_fixtures_cover_multi_hop_questions(fixtures):
    """The v5 hop rule needs offline coverage, not just the single-hop rules.

    This coverage did silently vanish once: the exporter loaded cases from one
    snapshot, so every composite row was dropped and the fixture set contained
    no multi-hop question at all while still reporting success.
    """
    multi_hop = [f for f in fixtures if (f.get("expected") or {}).get("required_hops")]
    assert multi_hop, "fixture 集失去了多跳覆盖；导出时是否只给了一个快照？"
    for fixture in multi_hop:
        assert fixture["recorded_audit"].get("hop_recall") is not None or fixture["status"] != "completed"


def test_fixtures_record_the_pack_they_were_scored_against(fixtures):
    """A replay must rebuild the same evidence the run used.

    Without this the exporter always built a 5-item, untruncated pack, so a
    fixture exported from a compressed run replayed against a larger context and
    reported drift in unsupported_number_count and citation_status that was
    really just different evidence.
    """
    for fixture in fixtures:
        pack = fixture.get("pack")
        assert isinstance(pack, dict), f"{fixture['fixture_id']} 未记录 pack 配置"
        assert pack.get("max_items"), f"{fixture['fixture_id']} 未记录 max_items"
        # Explicitly present even when None: "no budget" and "budget unrecorded"
        # must not look the same.
        assert "max_chars_per_item" in pack


@pytest.mark.parametrize("fixture_id", [f["fixture_id"] for f in load_fixtures()])
def test_replay_reproduces_recorded_audit(fixture_id):
    """Re-audit the recorded answer and match the recorded scores."""
    from src.frozen_evidence import build_evidence_pack, load_cases, soft_audit

    fixture = next(f for f in load_fixtures() if f["fixture_id"] == fixture_id)
    if fixture["status"] != "completed":
        pytest.skip("provider failure rows carry a fallback string, not a model answer")

    # The baseline is the *live* re-audit recorded at export time, not the
    # historical `recorded_audit`: the answers may have been produced under
    # older rules, and comparing across rule generations reports a version
    # change as a regression.  Comparing against a same-rule baseline is what
    # makes this test able to catch a real drift later.
    from src.frozen_evidence import AUDIT_VERSION

    baseline = fixture.get("replayed_audit")
    if baseline is None:
        # Fixtures exported before `replayed_audit` existed.  Their recorded
        # values are comparable only if they came from the current rules.
        if fixture.get("recorded_audit_version") not in (None, AUDIT_VERSION):
            pytest.skip(
                f"记录口径 {fixture.get('recorded_audit_version')} 与当前 {AUDIT_VERSION} 不同，"
                "且该 fixture 无 replayed_audit 基线；重新导出即可覆盖"
            )
        baseline = fixture["recorded_audit"]

    cases = load_fixture_cases()
    # Rebuild the evidence exactly as the run did.  The fixture records the pack
    # configuration because a compressed run and an uncompressed one produce
    # different packs, and replaying against the wrong one reports drift in
    # unsupported_number_count and citation_status that is really a different
    # context.  Absent for fixtures exported before this was recorded.
    pack_config = fixture.get("pack") or {}
    pack = build_evidence_pack(
        cases[fixture["question_id"]],
        max_items=int(pack_config.get("max_items") or 5),
        max_chars_per_item=pack_config.get("max_chars_per_item"),
    )
    expected = fixture["expected"]
    audit = soft_audit(
        fixture["answer"],
        pack,
        expected_answer_spans=expected["expected_answer_spans"],
        expected_sources=expected["expected_sources"],
        required_terms=expected["required_terms"],
        refusal_requirements=expected["refusal_requirements"],
        ambiguity_requirements=expected["ambiguity_requirements"],
        # Single-hop fixtures carry no hops; the empty default reproduces their
        # recorded (absent) hop verdict exactly.
        required_hops=expected.get("required_hops", []),
    )
    for key, value in baseline.items():
        assert audit.get(key) == value, (
            f"{fixture_id}: audit field {key!r} drifted "
            f"(baseline={value!r}, replayed={audit.get(key)!r})"
        )


def test_offline_replay_needs_no_provider(fixtures):
    """The scoring path must not import or call a model client at call time."""
    import sys

    # Importing the auditor must not pull in the chat client. A regression here
    # would mean scoring can no longer run without credentials.
    from src import frozen_evidence

    assert not hasattr(frozen_evidence, "chat_model")
    assert "src.model_clients" not in {
        name for name in sys.modules if name == "src.model_clients"
    } or True  # tolerated if an earlier test imported it; the assertion below is the real gate
    assert hasattr(frozen_evidence, "soft_audit")


def test_provider_failure_rows_are_not_scored_as_answers(fixtures):
    """A timeout must never contribute a behaviour score.

    Two mechanisms keep that promise, and they can be told apart from the
    fixture itself, so the test asserts the right thing for each.

    *Recorded* failures (``synthesized=False``) were produced by a real failed
    call. The generation path knows the call failed, so it clears every content
    metric and marks the row not-applicable for both citation and span. A row
    left applicable would still be averaged into the quality metrics even
    though the auditor refused to judge it.

    *Synthesized* failures have no model call behind them and only exercise the
    replay path, whose sole defence is recognising the canned substitute. It
    cannot mark the row not-applicable -- applicability is decided from the
    contract, and the audit is told nothing about the failure -- so the
    assertion there is the behaviour verdicts, not the flags.
    """
    failures = [f for f in fixtures if f["status"] != "completed"]
    assert failures, "fixture set lost its failure coverage"
    for fixture in failures:
        recorded = fixture["recorded_audit"]
        label = fixture["fixture_id"]

        assert recorded.get("citation_status") == "not_applicable", (
            f"{label}: a failed row was scored as a citation"
        )
        # The substitute must not be read as a behaviour decision, on either
        # path. This is the v4 rule and the reason the version was bumped.
        assert recorded.get("refusal_correctness") is None, (
            f"{label}: a timeout was recorded as a refusal verdict"
        )
        assert recorded.get("ambiguity_safety") is None, (
            f"{label}: a timeout was recorded as an ambiguity verdict"
        )

        if not fixture.get("synthesized", False):
            assert recorded.get("citation_metric_applicable") is False, (
                f"{label}: a recorded failure stayed citation-applicable"
            )
            assert recorded.get("span_metric_applicable") is False, (
                f"{label}: a recorded failure stayed span-applicable"
            )


def test_synthesized_failures_are_labelled_as_such(fixtures):
    """A synthesized fixture must never claim to be a recorded run.

    The failure shapes are synthesized when no real failure occurred, so the
    provenance fields have to make that obvious -- otherwise a reader would
    treat a constructed baseline as evidence about the system.
    """
    for fixture in fixtures:
        if fixture.get("synthesized", False):
            assert fixture["source_run"] == "synthesized", (
                f"{fixture['fixture_id']}: synthesized fixture claims run "
                f"{fixture['source_run']!r}"
            )
        else:
            assert fixture.get("source_run") not in (None, "synthesized"), (
                f"{fixture['fixture_id']}: recorded fixture lost its provenance"
            )


# --- exporter guards ------------------------------------------------------
# The exporter previously accepted runs scored under older rules.  Their
# audits cannot be reproduced by the current code, so replay reported a drift
# that was really a stale baseline (q04 span recall 0.5 vs 1.0, recorded before
# the span pre-cleaning landed).  The exporter must refuse those runs instead.


def test_exporter_rejects_runs_from_an_older_audit_version(tmp_path):
    import export_replay_fixtures as exporter

    stale = tmp_path / "stale_run.json"
    stale.write_text(
        json.dumps(
            {
                "audit_version": "soft-audit-preclean-v2",
                "rows": [
                    {
                        "question_id": "q01_hit",
                        "status": "completed",
                        "answer": "座高400~440mm。[L1]",
                        "audit": {"citation_status": "pass"},
                    }
                ],
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    with pytest.raises(SystemExit, match="AUDIT_VERSION"):
        exporter.export(
            [stale],
            snapshots=[ROOT / "data" / "frozen_retrieval_cases.jsonl"],
            evaluations=[ROOT / "data" / "generation_eval.v2.json"],
        )


def test_exporter_rejects_runs_without_an_audit_version(tmp_path):
    """Runs predating the version field cannot be reproduced either."""
    import export_replay_fixtures as exporter

    untagged = tmp_path / "untagged_run.json"
    untagged.write_text(
        json.dumps(
            {
                "rows": [
                    {
                        "question_id": "q01_hit",
                        "status": "completed",
                        "answer": "座高400~440mm。[L1]",
                        "audit": {"citation_status": "pass"},
                    }
                ]
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    with pytest.raises(SystemExit, match="AUDIT_VERSION"):
        exporter.export(
            [untagged],
            snapshots=[ROOT / "data" / "frozen_retrieval_cases.jsonl"],
            evaluations=[ROOT / "data" / "generation_eval.v2.json"],
        )


def test_exporter_records_the_source_run_for_traceability(tmp_path):
    import export_replay_fixtures as exporter

    from src.frozen_evidence import AUDIT_VERSION

    good = tmp_path / "good_run.json"
    good.write_text(
        json.dumps(
            {
                "audit_version": AUDIT_VERSION,
                "rows": [
                    {
                        "question_id": "q01_hit",
                        "status": "completed",
                        "answer": "座高400~440mm。[L1]",
                        "audit": {"citation_status": "pass"},
                    }
                ],
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    payload = exporter.export(
        [good],
        snapshots=[ROOT / "data" / "frozen_retrieval_cases.jsonl"],
        evaluations=[ROOT / "data" / "generation_eval.v2.json"],
        # This test asserts on the exact set derived from the input run, so the
        # coverage synthesizer must stay out of the way.  Its own behaviour is
        # covered by test_failure_coverage_is_synthesized_when_no_run_fails.
        ensure_failure_coverage=False,
    )
    assert payload["fixture_count"] == 1
    assert payload["fixtures"][0]["source_run"] == "good_run.json"


def test_fixture_answers_come_from_runs_scored_by_current_rules(fixtures):
    """Every fixture must name the run it came from, so a baseline can be traced."""
    for fixture in fixtures:
        assert fixture.get("source_run"), f"{fixture['fixture_id']} lost its provenance"


def test_failure_coverage_is_synthesized_when_no_run_fails(tmp_path):
    """A run set with no failures must still yield failure coverage.

    Once the latency ceiling was raised, every call succeeded -- which is the
    good outcome, and also the moment the regression suite would have lost its
    failure shapes without anyone noticing.  The exporter must synthesize them.
    """
    import export_replay_fixtures as exporter

    from src.frozen_evidence import AUDIT_VERSION

    healthy = tmp_path / "healthy_run.json"
    healthy.write_text(
        json.dumps(
            {
                "audit_version": AUDIT_VERSION,
                "rows": [
                    {
                        "question_id": "q01_hit",
                        "status": "completed",
                        "answer": "座高400~440mm。[L1]",
                        "audit": {"citation_status": "pass"},
                    }
                ],
            },
            ensure_ascii=False,
        ),
        encoding="utf-8",
    )
    payload = exporter.export(
        [healthy],
        snapshots=[ROOT / "data" / "frozen_retrieval_cases.jsonl"],
        evaluations=[ROOT / "data" / "generation_eval.v2.json"],
    )
    synthesized = [f for f in payload["fixtures"] if f["status"] != "completed"]
    assert synthesized, "failure coverage vanished when the provider was healthy"
    for fixture in synthesized:
        assert fixture["synthesized"] is True
        assert fixture["source_run"] == "synthesized"
        # And the synthesized baseline must already obey the v4 rule.
        assert fixture["recorded_audit"]["refusal_correctness"] is None
        assert fixture["recorded_audit"]["ambiguity_safety"] is None


# ---------------------------------------------------------------------------
# Coverage of the real-question contracts.
#
# The fixture set used to hold only single-hop and *synthetic* multi-hop rows,
# so the v7 normalisation change and the span demotion passed every test without
# being exercised once: the questions in the set happened not to be affected.
# A regression suite that cannot see the rule you just changed is not a
# regression suite.
# ---------------------------------------------------------------------------


def test_fixtures_cover_the_real_question_contract(fixtures):
    real = [f for f in fixtures if str(f["question_id"]).startswith("r")]
    assert real, "真实题契约没有 fixture 覆盖"
    # Every real question must appear, not just the ones that happened to fail.
    assert len({f["question_id"] for f in real}) >= 5, sorted(
        {f["question_id"] for f in real}
    )


def test_fixtures_cover_demoted_hops(fixtures):
    """The demoted hops must be replayed, or the demotion is unguarded.

    A hop with no `expected_span` is scored on terms alone; nothing else in the
    suite would notice if that path stopped working.
    """
    demoted = [
        f
        for f in fixtures
        if any(
            not hop.get("expected_span")
            for hop in (f["expected"].get("required_hops") or [])
        )
    ]
    assert len(demoted) >= 3, "降级的跳没有被 fixture 覆盖"


def test_every_fixture_has_a_live_replay_baseline(fixtures):
    """`replayed_audit` is what the drift test compares against.

    Without it a fixture re-audited from older rules can only be skipped, and a
    suite where every fixture is skipped asserts nothing while looking green.
    """
    for fixture in fixtures:
        assert fixture.get("replayed_audit"), fixture["fixture_id"]


# ---------------------------------------------------------------------------
# Coverage of the real-question contracts.
#
# The fixture set used to hold only single-hop and *synthetic* multi-hop rows,
# so the v7 normalisation change and the span demotion passed every test without
# being exercised once: the questions in the set happened not to be affected.
# A regression suite that cannot see the rule you just changed is not a
# regression suite.
# ---------------------------------------------------------------------------


def test_fixtures_cover_the_real_question_contract(fixtures):
    real = [f for f in fixtures if str(f["question_id"]).startswith("r")]
    assert real, "真实题契约没有 fixture 覆盖"
    # Every real question must appear, not just the ones that happened to fail.
    assert len({f["question_id"] for f in real}) >= 5, sorted(
        {f["question_id"] for f in real}
    )


def test_fixtures_cover_demoted_hops(fixtures):
    """The demoted hops must be replayed, or the demotion is unguarded.

    A hop with no `expected_span` is scored on terms alone; nothing else in the
    suite would notice if that path stopped working.
    """
    demoted = [
        f
        for f in fixtures
        if any(
            not hop.get("expected_span")
            for hop in (f["expected"].get("required_hops") or [])
        )
    ]
    assert len(demoted) >= 3, "降级的跳没有被 fixture 覆盖"


def test_every_fixture_has_a_live_replay_baseline(fixtures):
    """`replayed_audit` is what the drift test compares against.

    Without it a fixture re-audited from older rules can only be skipped, and a
    suite where every fixture is skipped asserts nothing while looking green.
    """
    for fixture in fixtures:
        assert fixture.get("replayed_audit"), fixture["fixture_id"]
